
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_site_plugin_events` DISABLE KEYS */;
REPLACE INTO `modx_site_plugin_events` VALUES (9,'OnWebPagePrerender',-100,0);
REPLACE INTO `modx_site_plugin_events` VALUES (2,'OnRichTextBrowserInit',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (2,'OnRichTextEditorRegister',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (2,'OnRichTextEditorInit',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (17,'OnManagerAuthentication',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (17,'OnManagerPageInit',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (17,'OnDocFormSave',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (17,'OnManagerPageBeforeRender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (17,'OnManagerPageAfterRender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (13,'OnManagerPageBeforeRender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (9,'OnMODXInit',-100,0);
REPLACE INTO `modx_site_plugin_events` VALUES (9,'OnSiteRefresh',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (9,'OnBeforeSaveWebPageCache',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (18,'OnPluginFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (18,'OnChunkFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (17,'OnTempFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (17,'OnDocFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (17,'OnLoadWebDocument',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (17,'OnMODXInit',-100,0);
REPLACE INTO `modx_site_plugin_events` VALUES (18,'OnSnipFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (18,'OnTempFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (18,'OnFileEditFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (18,'OnFileCreateFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (18,'OnDocFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (18,'OnRichTextEditorRegister',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (18,'OnManagerPageBeforeRender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (19,'OnManagerPageBeforeRender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (19,'OnBeforeRegisterClientScripts',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (20,'OnManagerPageBeforeRender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (21,'OnFileManagerUpload',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (22,'OnDocFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (22,'OnTVInputPropertiesList',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (22,'OnTVInputRenderList',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (23,'OnDocFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (24,'OnFileManagerUpload',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (25,'OnMODXInit',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (25,'OnHandleRequest',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (25,'OnLoadWebDocument',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (25,'OnWebPageInit',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (25,'OnUserSave',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (25,'msOnChangeOrderStatus',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (25,'OnManagerPageBeforeRender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (26,'OnManagerPageBeforeRender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (27,'OnTempFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (27,'OnDocFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (27,'OnChunkFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (27,'OnSnipFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (27,'OnTempFormSave',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (27,'OnDocFormSave',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (27,'OnChunkFormSave',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (28,'OnHandleRequest',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (29,'OnChunkFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (29,'OnDocFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (29,'OnTempFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (29,'OnSnipFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (29,'OnPluginFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (29,'OnFileEditFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (30,'OnMODXInit',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (30,'OnDocFormRender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (30,'OnDocFormSave',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (30,'OnResourceDuplicate',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (30,'OnLoadWebDocument',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (31,'OnDocFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (31,'OnBeforeDocFormSave',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (31,'OnLoadWebDocument',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (31,'OnPageNotFound',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (31,'OnResourceDuplicate',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (31,'OnManagerPageBeforeRender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (31,'OnResourceBeforeSort',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (31,'OnDocFormSave',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (31,'OnEmptyTrash',0,0);
/*!40000 ALTER TABLE `modx_site_plugin_events` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

