
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_actions_fields` DISABLE KEYS */;
REPLACE INTO `modx_actions_fields` VALUES (1667,'resource/create','pub_date','field','modx-page-settings-right','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1666,'resource/create','publishedon','field','modx-page-settings-right','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1665,'resource/create','modx-page-settings-right','tab','','modx-panel-resource','',5);
REPLACE INTO `modx_actions_fields` VALUES (1664,'resource/create','menuindex','field','modx-page-settings-left','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1663,'resource/create','content_dispo','field','modx-page-settings-left','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1662,'resource/create','content_type','field','modx-page-settings-left','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1661,'resource/create','class_key','field','modx-page-settings-left','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1660,'resource/create','parent-cmb','field','modx-page-settings-left','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1659,'resource/create','modx-page-settings-left','tab','','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1658,'resource/create','modx-page-settings','tab','','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1657,'resource/create','published','field','modx-resource-main-right','modx-panel-resource','',5);
REPLACE INTO `modx_actions_fields` VALUES (1656,'resource/create','hidemenu','field','modx-resource-main-right','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1655,'resource/create','link_attributes','field','modx-resource-main-right','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1654,'resource/create','menutitle','field','modx-resource-main-right','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1653,'resource/create','alias','field','modx-resource-main-right','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1652,'resource/create','template','field','modx-resource-main-right','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1651,'resource/create','modx-resource-main-right','tab','','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1650,'resource/create','introtext','field','modx-resource-main-left','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1649,'resource/create','description','field','modx-resource-main-left','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1648,'resource/create','longtitle','field','modx-resource-main-left','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1647,'resource/create','pagetitle','field','modx-resource-main-left','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1646,'resource/create','id','field','modx-resource-main-left','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1645,'resource/create','modx-resource-main-left','tab','','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1644,'resource/create','modx-resource-settings','tab','','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1643,'resource/update','modx-weblink-content','field','modx-resource-content','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1642,'resource/update','modx-symlink-content','field','modx-resource-content','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1641,'resource/update','modx-resource-content','field','modx-resource-content','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1640,'resource/update','modx-resource-access-permissions','tab','','modx-panel-resource','',9);
REPLACE INTO `modx_actions_fields` VALUES (1639,'resource/update','modx-panel-resource-tv','tab','','modx-panel-resource','tv',8);
REPLACE INTO `modx_actions_fields` VALUES (1638,'resource/update','deleted','field','modx-page-settings-right-box-right','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1637,'resource/update','syncsite','field','modx-page-settings-right-box-right','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1636,'resource/update','cacheable','field','modx-page-settings-right-box-right','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1635,'resource/update','modx-page-settings-right-box-right','tab','','modx-panel-resource','',7);
REPLACE INTO `modx_actions_fields` VALUES (1634,'resource/update','uri','field','modx-page-settings-right-box-left','modx-panel-resource','',5);
REPLACE INTO `modx_actions_fields` VALUES (1633,'resource/update','uri_override','field','modx-page-settings-right-box-left','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1632,'resource/update','richtext','field','modx-page-settings-right-box-left','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1631,'resource/update','alias_visible','field','modx-page-settings-right-box-left','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1630,'resource/update','searchable','field','modx-page-settings-right-box-left','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1629,'resource/update','isfolder','field','modx-page-settings-right-box-left','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1628,'resource/update','modx-page-settings-right-box-left','tab','','modx-panel-resource','',6);
REPLACE INTO `modx_actions_fields` VALUES (1627,'resource/update','unpub_date','field','modx-page-settings-right','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1626,'resource/update','pub_date','field','modx-page-settings-right','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1625,'resource/update','publishedon','field','modx-page-settings-right','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1624,'resource/update','modx-page-settings-right','tab','','modx-panel-resource','',5);
REPLACE INTO `modx_actions_fields` VALUES (1623,'resource/update','menuindex','field','modx-page-settings-left','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1622,'resource/update','content_dispo','field','modx-page-settings-left','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1621,'resource/update','content_type','field','modx-page-settings-left','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1620,'resource/update','class_key','field','modx-page-settings-left','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1619,'resource/update','parent-cmb','field','modx-page-settings-left','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1618,'resource/update','modx-page-settings-left','tab','','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1617,'resource/update','modx-page-settings','tab','','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1616,'resource/update','published','field','modx-resource-main-right','modx-panel-resource','',5);
REPLACE INTO `modx_actions_fields` VALUES (1615,'resource/update','hidemenu','field','modx-resource-main-right','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1614,'resource/update','link_attributes','field','modx-resource-main-right','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1613,'resource/update','menutitle','field','modx-resource-main-right','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1612,'resource/update','alias','field','modx-resource-main-right','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1611,'resource/update','template','field','modx-resource-main-right','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1610,'resource/update','modx-resource-main-right','tab','','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1609,'resource/update','introtext','field','modx-resource-main-left','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1608,'resource/update','description','field','modx-resource-main-left','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1607,'resource/update','longtitle','field','modx-resource-main-left','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1606,'resource/update','pagetitle','field','modx-resource-main-left','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1605,'resource/update','id','field','modx-resource-main-left','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1604,'resource/update','modx-resource-main-left','tab','','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1603,'resource/update','modx-resource-settings','tab','','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1668,'resource/create','unpub_date','field','modx-page-settings-right','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1669,'resource/create','modx-page-settings-right-box-left','tab','','modx-panel-resource','',6);
REPLACE INTO `modx_actions_fields` VALUES (1670,'resource/create','isfolder','field','modx-page-settings-right-box-left','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1671,'resource/create','searchable','field','modx-page-settings-right-box-left','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1672,'resource/create','alias_visible','field','modx-page-settings-right-box-left','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1673,'resource/create','richtext','field','modx-page-settings-right-box-left','modx-panel-resource','',3);
REPLACE INTO `modx_actions_fields` VALUES (1674,'resource/create','uri_override','field','modx-page-settings-right-box-left','modx-panel-resource','',4);
REPLACE INTO `modx_actions_fields` VALUES (1675,'resource/create','uri','field','modx-page-settings-right-box-left','modx-panel-resource','',5);
REPLACE INTO `modx_actions_fields` VALUES (1676,'resource/create','modx-page-settings-right-box-right','tab','','modx-panel-resource','',7);
REPLACE INTO `modx_actions_fields` VALUES (1677,'resource/create','cacheable','field','modx-page-settings-right-box-right','modx-panel-resource','',0);
REPLACE INTO `modx_actions_fields` VALUES (1678,'resource/create','syncsite','field','modx-page-settings-right-box-right','modx-panel-resource','',1);
REPLACE INTO `modx_actions_fields` VALUES (1679,'resource/create','deleted','field','modx-page-settings-right-box-right','modx-panel-resource','',2);
REPLACE INTO `modx_actions_fields` VALUES (1680,'resource/create','modx-panel-resource-tv','tab','','modx-panel-resource','tv',8);
REPLACE INTO `modx_actions_fields` VALUES (1681,'resource/create','modx-resource-access-permissions','tab','','modx-panel-resource','',9);
REPLACE INTO `modx_actions_fields` VALUES (1682,'resource/create','modx-resource-content','field','modx-resource-content','modx-panel-resource','',0);
/*!40000 ALTER TABLE `modx_actions_fields` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

